# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7128a730035d0056ecbe2c0bb96fb4d9f9b1b742758cc0cc00c69da1d7d09160a77b6cef915f790e7e878c70776bcf7d89af264ec73a2d30654724eaf4b3d6ed

test:
  secret_key_base: 251785fae87a999db41a8d9051812e4e32e7e85380d0626f8f8f1d5a31c59b6b348042aec9216b7c25363611d9930ec63d7d384b1a47c9fa7730e015e5682208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
